name: ci

on: [push, pull_request]

env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-DEV-500-TLS-5-2-area-saad.berrada.git

jobs:
  push_to_mirror:
    needs: [docker_compose, docker_updates]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.MIRROR_SSH_PRIVATE_KEY }}

  docker_compose:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.11
        ports:
          - 8080:80
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
  
      - name: Set up Docker Compose
        run: |
          docker-compose --version
          sudo apt-get install -y docker-compose
  
      - name: Build and run containers
        run: |
          docker-compose up -d --build
          docker-compose ps
          sleep 10  # Allow some time for the containers to start
      
      - name: Stop containers
        run: docker-compose down
  
  docker_updates:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.11
        ports:
          - 8080:80
    steps:
      - name: login to docker mongo
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: tag image mongo
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/area_mongo:latest ${{ secrets.DOCKER_USERNAME }}/area_mongo:latest
      - name: push image mongo
        run: docker push ${{ secrets.DOCKER_USERNAME }}/area_mongo:latest
      - name: login to docker back
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
      - name: tag image back
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/area_back:latest ${{ secrets.DOCKER_USERNAME }}/area_back:latest
      - name: push image back
        run: docker push ${{ secrets.DOCKER_USERNAME }}/area_back:latestError: Cannot perform an interactive login from a non TTY device
